homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 306
  unit_system: imperial
  time_zone: America/New_York

frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_pass
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

updater:
discovery:
conversation:
history:
logbook:
sun:

sensor:
  platform: yr

tts:
  platform: google

mqtt:
    embedded:
    broker: localhost
    port: 1883

switch:
  platform: mqtt
  name: "master closet"
  state_topic: "smartthings/master closet/switch"
  command_topic: "smartthings/master closet/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

switch 1:
  platform: mqtt
  name: "kitchen cabinets"
  state_topic: "smartthings/kitchen cabinets/switch"
  command_topic: "smartthings/kitchen cabinets/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
  
