homeassistant:
  name: Home
  latitude: 34.133
  longitude: -84.3005
  elevation: 306
  unit_system: imperial
  time_zone: America/New_York

frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

updater:
discovery:
conversation:
history:
logbook:
sun:

sensor:
  platform: yr

tts:
  platform: google

mqtt:
  embedded:
    listeners:
      default:
        max-connections: 500
        type: tcp
        bind: 127.0.0.1:1888
  broker: 127.0.0.1
  port: 1888
